Traceback (most recent call last):
  File "C:\Users\tbeucler\.conda\envs\JB\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\tbeucler\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\tbeucler\.conda\envs\JB\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\tbeucler\.conda\envs\JB\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\tbeucler\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\tbeucler\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\tbeucler\.conda\envs\JB\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Write your code here
PlayListRating = [10, 9.5, 10, 8, 7.5, 5, 10, 10]

# Hint: Use list indexing as a criteria (size of your list)
indx = 0
while ____<len(______________):
  if ____________[____]<6:
    ____
  else:
    print(_________[____])
  ____+=1
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[1], line 6[0m
[0;32m      4[0m [38;5;66;03m# Hint: Use list indexing as a criteria (size of your list)[39;00m
[0;32m      5[0m indx [38;5;241m=[39m [38;5;241m0[39m
[1;32m----> 6[0m [38;5;28;01mwhile[39;00m [43m____[49m[38;5;241m<[39m[38;5;28mlen[39m(______________):
[0;32m      7[0m   [38;5;28;01mif[39;00m ____________[____][38;5;241m<[39m[38;5;241m6[39m:
[0;32m      8[0m     ____

[1;31mNameError[0m: name '____' is not defined

